### ISSUE TITLE
Home Assistant Caldav not loading recurring events

### ISSUE THREAD

**Issue by asdrolf** [haberda/hassio_addons#10]
Not sure if its nexcloud bug or HA or if I'am doing something wrong. I'am not able to sync recurring events to HA using CalDav integration. I search and found some posts of other people with similar problems. is there some fix or workarround?

**Comment by haberda** [comment]
Hi. Unfortunately I do not have an answer to your question.

This add-on is just the linuxserver image packaged so that you can use it as an add-on. I suggest you ask upstream. I personally have not tried to use the caldav integration, if you find an answer let me know. Sorry.

Upstream:
https://docs.linuxserver.io/images/docker-nextcloud

**Comment by haberda** [comment]
After some experimenting, I think this is a home-assistant bug. Closing for now.

**Comment by asdrolf** [comment]
seems to me to
