### ISSUE TITLE
Pull request Nextcloud addon to Homeassistant HassIO

### ISSUE THREAD

**Issue by Erriez** [haberda/hassio_addons#11]
Hi @haberda,

Thanks for your great work to add Nextcloud support for HassIO. I got it up and running according to the README.md.

Do you have plans to create a pull request to https://github.com/home-assistant/addons? It was pretty hard to find this repository and is probably useful for other users.

Thanks,
Erriez

**Comment by haberda** [comment]
Hi @Erriez 

I doubt they would accept it. The official repository only takes add-ons that directly integrate with home-assistant. This add-on is just a repacked version of the linuxserver docker image and doesn't communicate with Home-assistant in any way (outside of normal integration). I agree official, nextcloud support would great, I made this add-on (and the rest) because I was frustrated that it wasn't available.

This repository started with the Signal add-on. As a signal user I was excited that there was finally an integration about a year ago. But the official docs tell you that you have to use a docker image to make the integration work. There was no add-on made so that HassOs users could use Signal. If you ran HassOs you'd have to run docker on another computer. So I packaged the docker container into an add-on and submitted a pull request to the 'community' add-on repo. It was rejected because they didn't want to maintain any new add-ons. So I put it here, and put a pull request in to at least update the docs so people could use it. That was accepted

I understand where they were coming from, at some point it grows too large to properly maintain with a small team, but it (Signal add-on) does directly support a native integration.

All that to say, I really doubt this Nextcloud add-on would be accepted, at least not in the current form.

I would like to get ingress working with this add-on (and others) as well, but I can't figure it out. I'm not really a programmer, just a hobbiest.

Thanks for your interest. If you want to make a branch and try your luck feel free.

**Comment by Erriez** [comment]
Hi @haberda,

Thanks for your fast reply. I did some more research on it and discovered that there are two add-on flavors: Add-ons which are maintained by Homeassistant (only a few) and add-ons maintained by community. I've asked some questions to add this to the list: https://community.home-assistant.io/t/add-on-request-nextcloud/192367

> So I packaged the docker container into an add-on and submitted a pull request to the 'community' add-on repo. It was rejected because they didn't want to maintain any new add-ons.

Interesting. Good news is that it is up and running, maybe someone wants to maintain it. I'll check the source how you configured this Docker so I can develop my own containers as well.

Thanks!
