### ISSUE TITLE
Signal Docker doesn't start

### ISSUE THREAD

**Issue by dreem2001** [haberda/hassio_addons#2]
Hello. I can't start the container under hassio supervisor. It fails with file not found exception.
Docker file contains ENTRYPOINT ["main", "-signal-cli-config", "/data/"] and code supports the second flag but not first. So I believe it's executable. The real executable is signal-cli-rest-api.
Could you check?

**Comment by markmghali** [comment]
I am also having the same issue. 

Thank you for creating this

**Comment by nurse-curtis** [comment]
Yes that's exactly it.  I the entrypoint to [

> Hello. I can't start the container under hassio supervisor. It fails with file not found exception.
> Docker file contains ENTRYPOINT ["main", "-signal-cli-config", "/data/"] and code supports the second flag but not first. So I believe it's executable. The real executable is signal-cli-rest-api.
> Could you check?

You're correct, I switched it on a local copy of the Dockerfile and it works perfectly now

**Comment by markmghali** [comment]
I ended up ditching this add-on. I wish it worked. 

I got the original signal cli docker working in unraid OS just fine.

**Comment by bbernhard** [comment]
The issue should be fixed with this pull request here: https://github.com/haberda/hassio_addons/issues/2

(I recently renamed the binary from "main" to "signal-cli-rest-api", see https://github.com/bbernhard/signal-cli-rest-api/blob/3b6957299209f14e2023268219e41fc32d5ec184/Dockerfile#L48 and wasn't aware that the binary's name is also used in the HA addon)

**Comment by skylyn** [comment]
@haberda I'm also having this problem. Anyway we can get the PR merged to fix this?

**Comment by haberda** [comment]
Sorry, wasn't getting notifications on this. Merged.
