### ISSUE TITLE
Signal Add-on: Add support for USE_NATIVE env

### ISSUE THREAD

**Issue by AlexanderBabel** [haberda/hassio_addons#24]
Hey,

could you please add support for the `USE_NATIVE` environment option?

It's a new experimental option from bbernhard: https://github.com/bbernhard/signal-cli-rest-api#native-image-experimental

I guess you could add a option for it. So that it is disabled by default, but can be enabled if the user wants to test the native version.

Thanks!

**Comment by haberda** [comment]
I'll look into it. I think a new upstream release is coming soon, so it will probably wait for that. The options that most add-ons have are easy to implement because most use the provided homeassistant images as a base which has support built in. This add-on does not, so it's not so easy to implement options. It would be easy enough to turn it on but not to have it as an option.

**Comment by haberda** [comment]
Use Native is now enabled by default as of version 0.37. If people have issues with it I may have to roll back, but my limited testing environment showed it to be pretty stable.

**Comment by speedst3r** [comment]
Doesn't work on arm64, there's an open issue on the upstream signal-cli-rest-api project.

**Comment by haberda** [comment]
Use Native is now an option on 0.37.2
