### ISSUE TITLE
how to access the CLI?

### ISSUE THREAD

**Issue by markmghali** [haberda/hassio_addons#4]
This is definitely user error how do I access the Command-line to register a phone number? I was able to do it very easily in unraid with docker. However, With this add-on I cannot wrap my head around how to go about doing it.

Thank you for your assistance.

**Comment by haberda** [comment]
I assume you mean the Signal add-on? This repo has several add-ons. I might move it to its own. 

This add-on uses a Rest API. The method is outlined in the official documentation:

https://www.home-assistant.io/integrations/signal_messenger/

And:

https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/HOMEASSISTANT.md

All you have to do it define the port and start the add-on. The Rest API will be available at the port you specify.

**Comment by markmghali** [comment]
There is still something I am missing/ not understanding after your explanation. How do I access the command line for this Signal Add-on. I cannot access terminal/command line from this add-on? or I do not know how?

**Comment by haberda** [comment]
There is no CLI that you access. This is a Rest API that you can access with something like Curl, the API then communicates to the CLI. To be clear, you run Curl in a CLI on some other machine, or on the host machine outside of the container. By default the API is available on port 8080. So to register a number:

curl -X POST -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/register/+431212131491291'

Would register 431212131491291 to Signal. You would then get an access code (lets pretend you get 123-456), to send that code back:

curl -X POST -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/register/+431212131491291/verify/123-456'

There are curl commands to send messages and create groups as well, but once it's registered you just setup the Home Assistant integration and hass will deal with sending messages.

**Comment by bijuabraham** [comment]
Hello,
I installed the add on, registered the phone, created the group. Was also able to send a message through CURL command.
But when I use the addon through HomeAssistant, I am getting the following error:

AddOn Logger: homeassistant.components.websocket_api.http.connection
Source: components/signal_messenger/notify.py:76
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:40:08 PM (2 occurrences)
Last logged: 2:43:34 PM

[548130965968] Couldn't determine REST API version
Following instructions here: https://www.home-assistant.io/integrations/signal_messenger/

Appreciate if you can provide any clue.
My YAML COnfiguration is as follows;
notify:
  - name: signal
    platform: signal_messenger
    url: "http://homeassistant.local:8080" # the URL where the Signal Messenger REST API is listening
    number: "+1XXXXXXXXXX" # the sender number
    recipients: # one or more recipients
      - "+1YYYYYYYYYY"

**Comment by bijuabraham** [comment]
Here's the full log incase it helps..

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/signal_messenger/notify.py:76
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:40:08 PM (3 occurrences)
Last logged: 3:12:09 PM

[548130965968] Couldn't determine REST API version
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f99dfec70>: Failed to establish a new connection: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='homeassistant.local', port=8080): Max retries exceeded with url: /v1/about (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99dfec70>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pysignalclirestapi/api.py", line 22, in api_info
    resp = requests.get(self._base_url + "/v1/about")
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='homeassistant.local', port=8080): Max retries exceeded with url: /v1/about (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99dfec70>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 149, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 128, in async_send_message
    await self.hass.async_add_executor_job(partial(self.send_message, message, **kwargs))  # type: ignore
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 79, in send_message
    raise ex
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 76, in send_message
    self._signal_cli_rest_api.send_message(message, self._recp_nrs, filenames)
  File "/usr/local/lib/python3.8/site-packages/pysignalclirestapi/api.py", line 45, in send_message
    api_versions, build_nr = self.api_info()
  File "/usr/local/lib/python3.8/site-packages/pysignalclirestapi/api.py", line 36, in api_info
    raise SignalCliRestApiError("Couldn't determine REST API version") from exc
pysignalclirestapi.api.SignalCliRestApiError: Couldn't determine REST API version`

**Comment by bijuabraham** [comment]
Ignore.. I changed homeassistant.local to localhost and it worked.

**Comment by bijuabraham** [comment]
Now the only issue is, I am unable to send to Groups. Getting this error:
{"error":"Failed to send message: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found\n"}% 

This happens from the Curl command also

**Comment by haberda** [comment]
Glad you were able to figure out out. 

I don't use signal groups with this add-on, so I am not sure what the problem is. This add-on is simply [this docker image](https://github.com/bbernhard/signal-cli-rest-api) packaged up for convenient use in Home Assistant, which in turn is simply a docker image of [this](https://github.com/AsamK/signal-cli) software. I actually don't know much about the internal workings of the container.

There is documentation as part of the Home Assistant [docs](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/HOMEASSISTANT.md) related to creating groups.

If I have time I will try and make some groups myself and see what happens.

**Comment by bijuabraham** [comment]
Actually, the problem is somewhere here:
curl -X GET -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/groups/<number>'

The group id then needs to be added to the Signal Messenger's recipients list in the configuration.yaml

it doesnt say what exactly is the group id. But I tried multiple variations and none of them work.
The get operations returns this:
`curl -X GET -H "Content-Type: application/json" 'http://homeassistant.local:8080/v1/groups/+1XXXXXXXXXX'
[{"name":"Home Alerts","id":"group.ZkFERWhRTDMxV01wbm53DDRhaG1Sdz09","internal_id":"fADEhQL31TMpnnwd4ahmRw==","members":["+1XXXXXXXXXX","+1YYYYYYYYYY"],"active":true,"blocked":false}]%  
`
I tried group.ZkFERWhRTDMxV01wbm53DDRhaG1Sdz09 and ZkFERWhRTDMxV01wbm53DDRhaG1Sdz09 and the internal ID fADEhQL31TMpnnwd4ahmRw==
None of them works.
I also tried an invalid phone number and noticed thats giving the same error. That means the error is related to group ID being wrong.

**Comment by haberda** [comment]
I just created a group following the docs link I provided above, worked fine. The group ID for home assistant is the one in your log:

`group.ZkFERWhRTDMxV01wbm53DDRhaG1Sdz09`

**Comment by bijuabraham** [comment]
I tried with "group." and its still giving the error
`
MacBook-Pro ~ % curl -X POST -H "Content-Type: application/json" -d '{"message": "Hello World!", "number": "+14087824582", "recipients": ["group.ZkFERWhRTDMxV01wbm53ZDRhaG1Sdz09"]}' 'http://homeassistant.local:8080/v1/send'
{"error":"Failed to send message: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found\n"}%                               MacBook-Pro ~ % 
`
Same command I try with phone number, its working
`MacBook-Pro ~ % curl -X POST -H "Content-Type: application/json" -d '{"message": "Hello World!", "number": "+1408782XXXX", "recipients": ["+1408242XXXX"]}' 'http://homeassistant.local:8080/v1/send'
null%
MacBook-Pro ~ % 
`
And here's the output from the Groups query
`
MacBook-Pro ~ % curl -X GET -H "Content-Type: application/json" 'http://homeassistant.local:8080/v1/groups/+1408782XXXX'
[{"name":"Home Alerts","id":"group.ZkFERWhRTDMxV01wbm53ZDRhaG1Sdz09","internal_id":"fADEhQL31WMpnnwd4ahmRw==","members":["+1408242XXXX","+1408782XXXX"],"active":true,"blocked":false}]%                                                                                                                      MacBook-Pro ~ % 
'

In the group you created, as you seeing the group as Legacy group ?
To the rest endpoint, are you using v1 ?

**Comment by bijuabraham** [comment]
I just created a new group and tried again with no luck. Full sequence of instructions.. Can you find any issue in the below that I am overlooking ?
`
MacBook-Pro ~ % curl -X POST -H "Content-Type: application/json" -d '{"name": "Home Alerts", "members": ["+1510946AAAA", "+1408242BBBB"]}' 'http://homeassistant.local:8080/v1/groups/+1408782XXXX'
{"id":"group.Q25yWDlVQll4NlF4YmVnSWlQMUJodz09"}%                                                                                                       MacBook-Pro ~ % curl -X POST -H "Content-Type: application/json" -d '{"message": "Hello World!", "number": "+1408782XXXX", "recipients": ["group.Q25yWDlVQll4NlF4YmVnSWlQMUJodz09"]}' 'http://homeassistant.local:8080/v1/send'
{"error":"Failed to send message: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found\n"}%                               MacBook-Pro ~ % 

I have only obfuscated the phone numbers above.
`

**Comment by haberda** [comment]
Only thing I can suggest is to use the actual IP address rather than the domain name. But like I said I am not too sure.

I get the same error trying to send to the group via the CLI, assuming your command is correct. But it works fine with home assistant.

It doesn't show it as a legacy group. I just made the group yesterday.
