### ISSUE TITLE
SSL certificates, docker volumes, and know hosts

### ISSUE THREAD

**Issue by jojolll** [haberda/hassio_addons#42]
Hello,
First of all, thank you for making and maintaining this Nextcloud add-on :) 
I open this issue for three questions, I do not know if this is the place, if not I would close it. 

1) Why the default SSL certificates are `/ssl/nextcloud/keys/cert.crt` and `/ssl/nextcloud/keys/cert.key` ?
Shouldn't they be /ssl/fullchain.pem and /ssl/privkey.pem, those generated by Let'sEncrypt? For my part I had to use Portainer to open root terminal in the container and modify the Nginx default site configuration file and use my LetsEncrypt certificates. 
If I'm wrong, wouldn't it be possible to add a parameter in the add-on configuration, like for example for the FTP addon?  
![image](https://user-images.githubusercontent.com/26553241/139667857-d3b6e3e9-78f6-4d94-821f-ffb02def4559.png)

2) Each time the module is restarted, a new docker volume is created and the old one is set to "unused" status. 
after first add-on boot : 
![image](https://user-images.githubusercontent.com/26553241/139668678-21215c45-03e3-44ef-93f3-305696684cf9.png)
after a reboot of the add-on :
![image](https://user-images.githubusercontent.com/26553241/139668673-4469e661-abda-4ac1-9899-80c691ed9b65.png)
I understand that this volume is useless since the mount point is `/config`, an empty folder since the configuration is stored in `/data/config/[...]`
![image](https://user-images.githubusercontent.com/26553241/139668820-033e165b-8fd7-49af-aa9d-ccd8645bb57a.png)
I think this happens because the container is destroyed at every stop. It is not just stopped and restarted, it is deleted and recreated. 
![image](https://user-images.githubusercontent.com/26553241/139668956-e42dc718-6e8f-4208-a8ff-9f97efe8b6ac.png)
Is this a normal behavior?

3) Since adding known domain names in the Nextcloud configuration is complex, you could advise in the module documentation to perform the configuration using the final domain name and not an internal address. 
Since I made the configuration like this, directly with `mydomain.com:8099`, I didn't need to add other authorized domains afterwards.

**Comment by haberda** [comment]
Hey there, no problem I'll try and answer them all, but I will say, most of what you are observing is just that I am not a developer and don't really know what I am doing.

1. To answer this I will just say that when I first made it I was pointing to those files, however Nextcloud was just overwriting them with one's that it generated, which would kill your certs. Since I was using a reverse proxy anyway I just let it be. Honestly, I really recommend a reverse proxy with any service you host anyway, that way you can use `nextcloud.yourdomain.com` without ports specified.
2. I have no idea whether it is normal or not. Home Assistant is handling the volumes, maybe I am not specifying something correctly, but I don't know and it's not documented in the Add-on developer docs. If you find something, let me know.
3. I can do that. You can also use the Portainer console to do the configuration so that is a third option. I will update when I get a chance.
