### ISSUE TITLE
Cannot Register Number Due to Timeout Errors. 

### ISSUE THREAD

**Issue by RJ-Make** [haberda/hassio_addons#65]
Hello,
  I've been trying to get Signal working inside the latest version of HAOS for the last month with little success. [Here is the support request](https://github.com/bbernhard/signal-cli-rest-api/issues/312)  

1st 'successful' batches of attempts: I kept hitting Timeout errors when trying to register the number. After ~40 attempts I was able to get the number registered and verified. ~6hrs later the system stopped working with some "Broken Pipe" error (see link above). 

So I started over. 

2st batches of attempts: I was able to get the number registered, again with a ton of attempts, but could not get it verified. Due to the same Timeout errors. This is where I'm stuck now.  We originally thought the timeout errors were on Signals side, but that is now very unlikely. 

```
Details:
Home Assistant 2022.12.8 
Supervisor 2022.12.1 
Operating System 9.4 
Frontend 20221213.1 - latest
Running in VMWare on a Windows 10 Host 
Addon About command {"versions":["v1","v2"],"build":2,"mode":"normal","version":"0.64"}
```

I have no communication issue (outgoing / incoming) with any other add-on / integration on my network.
I have tried to register inside HA using Terminal (results are the same)
I have tried registering outside HA using Gitbash (results are the same)
I have tried adjusting the timeout setting to 240 (results are the same)

I can set the logging to debug, but have no way of getting to the debug file(s)??

@bbernhard is going to release an update soon, would it be possible to get the add-on updated once that takes place?

Thank you for all your help.

**Comment by dan-s-github** [comment]
0.65 has been released few days ago, hope the add-on gets updated soon as I also struggle registering a number.

Thanks for actually creating this add-on for easy install into home assistant

**Comment by RJ-Make** [comment]
Thank you @haberda for rolling out an update. While this did not fix the problem, I really appreciate your hard work!

Is there a way to get to the advanced debug logs in HAOS?

**Comment by haberda** [comment]
> Thank you @haberda for rolling out an update. While this did not fix the problem, I really appreciate your hard work!
> 
> Is there a way to get to the advanced debug logs in HAOS?

You can directly access docker using the 'SSH and Web Terminal' add-on from the community store, if you disable protection mode. Otherwise this works exactly the same as the upstream container. All that is really different is an environment variable to move the persistent storage location, and a script to set other env variables based on the options that were chosen. So whatever tools you have with the upstream you have with the add-on. I don't know much about debug logging for the upstream. If there is an env variable I can set, I could add it as an option.

**Comment by dan-s-github** [comment]
I managed to link an existing number to home assistant after I deleted the add-on and re-installing it. Something had messed up the config inside the container from previous tries. 
After accessing the docker container directly I found an account.json file which looked okay but was missing the uuid.
Restarting from blank canvas fixed it and I can now send notifications from HA

Used web browser to get qr code instead of curl:
`http://<ha ip>:<port>/v1/qrcodelink?device_name=HomeAssistant`
scanned with signal app on iOS, device linked

**Comment by RJ-Make** [comment]
I think I figured out how to get to the container `docker exec -it addon_1315902c_signal_messenger /bin/bash` ? I saw there was a file named account.json, but didn't know how to open it. So I first used the add-on reset data function and that file went away. I then uninstalled and reinstalled the add-on.

 I tried again `curl -X POST -H "Content-Type: application/json" --data '{"use_voice": false}' 'http://127.0.0.1:8787/v1/register/+1XXXXXXXXXX'` in SSH and Web Terminal, the result is the same. (Time out Error)
 
 So I used the web browser suggestion by @dan-s-github to see if I could link my cell number using `http://192.168.1.132:8787/v1/qrcodelink?device_name=HomeAssistant` which returns 

`{"error":"Couldn't create QR code: no data to encode"}`

**Comment by haberda** [comment]
I am not sure about the browser method you tried, I have not heard of that.

However, one thing to note, if you are using 127.0.0.1 that is a loopback address. If you use that in a docker container, such as the web console addon, it stays in that container. The timeout happens because there is nothing listening on that endpoint inside the SSH and Web Terminal add-on container. The endpoint is in the Signal add-on container.

You have to either:
1. Use that actual machine address in either the SSH and Web Terminal add-on, or a standard linux console
2. Sign into the Signal add-on container via the SSH and Web Terminal add-on (via the docker command you used before) and use the loopback address

**Comment by dan-s-github** [comment]
@haberda 
requesting a qrcodelink is a standard get call according to https://bbernhard.github.io/signal-cli-rest-api/#/Devices/get_v1_qrcodelink only found this doc today but tried http because it was mentioned
here: https://github.com/bbernhard/signal-cli-rest-api/issues/95#issuecomment-779997323

@RJ-Make 
I followed this instructions to connect to the bash inside the container https://github.com/bbernhard/signal-cli-rest-api/issues/95#issuecomment-780084593 

- `docker ps` might complain that you need to restart ssh add-on with protection mode disabled
```
➜  ~ docker ps
CONTAINER ID   IMAGE                                                           COMMAND         CREATED              STATUS                PORTS                                       NAMES
...
2b35cd4a826e   ghcr.io/haberda/signal_messenger/aarch64:0.65.0                 "/options.sh"   2 days ago           Up 2 days (healthy)   0.0.0.0:8234->8080/tcp, :::8234->8080/tcp   addon_83ec9c64_signal_messenger
...
➜  ~ docker exec -it 2b35cd4a826e /bin/bash
WARNING: signal-cli-rest-api runs as signal-api (not as root!)
Run 'su signal-api' before using signal-cli!
If you want to use signal-cli directly, don't forget to specify the config directory. e.g: "signal-cli --config /data"
root@83ec9c64-signal-messenger:/data/data# ls
531648  531648.d  accounts.json
root@83ec9c64-signal-messenger:/data/data# cat accounts.json
{
  "accounts" : [ {
    "path" : "531648",
    "environment" : "LIVE",
    "number" : "XXXXXXXXXXXXX",
    "uuid" : "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
  } ],
  "version" : 2
}root@83ec9c64-signal-messenger:/data/data#
```
After a fresh install of the add-on the ls cmd should not show any files, they are created after successfully linking the device. 
Hope this helps

**Comment by RJ-Make** [comment]
> @haberda requesting a qrcodelink is a standard get call according to https://bbernhard.github.io/signal-cli-rest-api/#/Devices/get_v1_qrcodelink only found this doc today but tried http because it was mentioned here: [bbernhard/signal-cli-rest-api#95 (comment)](https://github.com/bbernhard/signal-cli-rest-api/issues/95#issuecomment-779997323)
> 
> @RJ-Make I followed this instructions to connect to the bash inside the container [bbernhard/signal-cli-rest-api#95 (comment)](https://github.com/bbernhard/signal-cli-rest-api/issues/95#issuecomment-780084593)
> 
>     * `docker ps` might complain that you need to restart ssh add-on with protection mode disabled
> 
> 
> ```
> ➜  ~ docker ps
> CONTAINER ID   IMAGE                                                           COMMAND         CREATED              STATUS                PORTS                                       NAMES
> ...
> 2b35cd4a826e   ghcr.io/haberda/signal_messenger/aarch64:0.65.0                 "/options.sh"   2 days ago           Up 2 days (healthy)   0.0.0.0:8234->8080/tcp, :::8234->8080/tcp   addon_83ec9c64_signal_messenger
> ...
> ➜  ~ docker exec -it 2b35cd4a826e /bin/bash
> WARNING: signal-cli-rest-api runs as signal-api (not as root!)
> Run 'su signal-api' before using signal-cli!
> If you want to use signal-cli directly, don't forget to specify the config directory. e.g: "signal-cli --config /data"
> root@83ec9c64-signal-messenger:/data/data# ls
> 531648  531648.d  accounts.json
> root@83ec9c64-signal-messenger:/data/data# cat accounts.json
> {
>   "accounts" : [ {
>     "path" : "531648",
>     "environment" : "LIVE",
>     "number" : "XXXXXXXXXXXXX",
>     "uuid" : "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
>   } ],
>   "version" : 2
> }root@83ec9c64-signal-messenger:/data/data#
> ```
> 
> After a fresh install of the add-on the ls cmd should not show any files, they are created after successfully linking the device. Hope this helps

That was a big help. So if it is indeed true that the accounts.json file only gets created after successfully linking the device then there is a problem. 

When I reset the data, the file gets deleted, however on a failed attempt to register the file is created and the content is:

![2023-01-11_15-18-23](https://user-images.githubusercontent.com/8496835/211909898-ddd2d682-9f26-446d-9f7c-9b1874e9e228.jpg)

**Comment by dan-s-github** [comment]
My comments are solely in regards of linking to a current device. I didn't get the register number working as it required a  captcha and this somehow never worked. When registering a new device you should get a UUID from the signal server but this seems to time out.
Did you try to run the curl cmd on a Linux, Mac or Windows (WSL) computer instead of doing it inside HA?
Also the curl in your screenshot is the register call and this is the one that seems to timeout.
Can you actually generate qrcodes with the browser method mentioned above?

**Comment by RJ-Make** [comment]
I don't really want to register my cell number, for the reasons listed in the installation and setup docs (but the http qrcodelink didn't work for me either) . 

I've tried running the curl command in Git Bash which ends with the same time out error.  It was using Git Bash that I was able to get it registered the one time, but after 6hours the add-on failed with a pipe error. 


So there is definitely something wrong with the add-on in HAOS, as there doesn't seem to be anyone else talking about time-out errors. 

I've tried everything I know, spent hours upon hours trying to get this to work and unless I can produce helpfull debug logs (no one seems where they are in HAOS Add-on) I guess I'm dead in the water. 

Thanks for your help @dan-s-github

**Comment by RJ-Make** [comment]
> I am not sure about the browser method you tried, I have not heard of that.
> 
> However, one thing to note, if you are using 127.0.0.1 that is a loopback address. If you use that in a docker container, such as the web console addon, it stays in that container. The timeout happens because there is nothing listening on that endpoint inside the SSH and Web Terminal add-on container. The endpoint is in the Signal add-on container.
> 
> You have to either:
> 
>     1. Use that actual machine address in either the SSH and Web Terminal add-on, or a standard linux console
> 
>     2. Sign into the Signal add-on container via the SSH and Web Terminal add-on (via the docker command you used before) and use the loopback address


I forgot to respond... 

Running the command in the container (using the docker exec -it and su signal-api to get there) ends with a `Failed to connect to 127.0.0.1:8787, Connection Refused`

Running the command in Git Bash in windows, using the machines IP, results in the same Time Out Error. 

Running the command in SSH and Web Terminal using the machines IP results in the same Time Out Error.

**Comment by dan-s-github** [comment]
I wonder if there is some firewall blocking the requests to the signal server?
In regards to running command inside container you would need to use port localhost:8080, 8787 is mapped to 8080 inside container, see ports in `docker ps` output. 
This is what I have using port 8234:
```
0.0.0.0:8234->8080/tcp, :::8234->8080/tcp
```

I tried to register another old mobile number I have and got a captcha required response.
```
➜  ~ curl -X POST -H "Content-Type: application/json" --data '{"use_voice": false}' 'http://127.0.0.1:8234/v1/register/+XXXXXXX'
{"error":"Captcha required for verification, use --captcha CAPTCHA\nTo get the token, go to https://signalcaptchas.org/registration/generate.html\nCheck the developer tools (F12) console for a failed redirect to signalcaptcha://\nEverything after signalcaptcha:// is the captcha token.\n"}#   
```
this creates an entry in the accounts.json which is missing the uuid.

So far I can tell that the add-on works fine in my environment

**Comment by RJ-Make** [comment]
Thanks once again. 

I guess it has something to do with running HOAS in VMware, as I installed Signal PC on the server that runs everything and it works just fine. 

I did try with :8080 and that now produces the same time out error. 

I'm running a UDMB and have all IPS, etc turned off which made no difference. 

This is some crazy stuff here, and without debug logs......

**Comment by dan-s-github** [comment]
you might need to try signal-cli directly, check https://github.com/AsamK/signal-cli/wiki/Quickstart

**Comment by RJ-Make** [comment]
> you might need to try signal-cli directly, check https://github.com/AsamK/signal-cli/wiki/Quickstart

So I muddled my way through installing Docker and running that install yml file. 

Had everything registered, verified, and a group created in less then 5 minutes (haven't tested sending any messages yet).

I have a couple of questions if you don't mind. (I no nothing about Docker)

1) How do I change the communication type to the rpc jason type? 

I shut down the container, changed the setting in the yml file, restarted the container, but it's still using normal. 

2) How do I auto start the container after I reboot Windows?

**Comment by dan-s-github** [comment]
my link to the QuickStart page was more to try the signal-cli api commands inside the add-on docker container.

I am not a docker expert and all I did so far was using instructions found on some links mentioned earlier.

But this should be discussed on your ticket here: https://github.com/bbernhard/signal-cli-rest-api/issues/312

I don't think it is an issue with the add-on
