### ISSUE TITLE
Cannot change/find config.php

### ISSUE THREAD

**Issue by The-May** [haberda/hassio_addons#7]
Hi,

the installation works on my NUC and 2fa works too after installing the TOTP NC-Addon etc.
Every documentation says I need to edit this file but I cannot change the config.php because I cannot imagine a way to edit it.

Is there a way to edit it easily or did I miss something out?
![grafik](https://user-images.githubusercontent.com/47433911/98555051-bebbf480-22a1-11eb-9c30-8d8f132b3230.png)

**Comment by haberda** [comment]
This file is stored in the /data folder in the nextcloud container. This is the persistent location that hassio addons keep config data. There is no way to access this directly on a hassos machine because they block filesystem access. 

You can remove the hard drive, plug it into another machine and navigate to it from there. It will be something like:

/usr/share/hassio/addons/data/1315902c_nextcloud

**Comment by The-May** [comment]
After fiddling around for something different, I enabled [Developer SSH](https://developers.home-assistant.io/docs/operating-system/debugging/) to lookup where it is.
The path is:
/mnt/data/supervisor/addons/data/1315902c_nextcloud/config/www/nextcloud/

then i copied the config to a path i can easily access through SMB, edited it and copied it to the original path back and overwrote the older config.

`cp /mnt/data/supervisor/addons/data/1315902c_nextcloud/config/www/nextcloud/config/config.php /mnt/data/supervisor/backup/
# cp /mnt/data/supervisor/backup/config.php /mnt/data/supervisor/addons/data/1315902c_nextcloud/config/www/nextcloud/config/
`

**Comment by haberda** [comment]
I found an alternate way to edit this file from the Nextcloud web interface. At this point you seem to have figured it out but nonetheless I have added the instructions to the readme file under the Nextcloud folder.
