### ISSUE TITLE
Cron.php  error

### ISSUE THREAD

**Issue by aladin2000** [haberda/hassio_addons#71]
using hassio addon   
Nextcloud for Home Assistant 2023.5.2 Supervisor 2023.04.1
Current version: 26.0.0 (Journal des modifications) 
( I précise that  I used the config.php   using /share/nextcloud instead of /data  )

I got that error 
Could not open input file: /config/www/nextcloud/cron.php 

I found that  workaround inside  the container but don't know if that is enough to fix ... 
`ln -s /data/config/www /config/www`

for instance I red that in nexcloud, there is the MODS who take in account such a crron availability like the following variables:

 **In any container docker arguments, set an environment variable DOCKER_MODS=linuxserver/mods:universal-cron**

Is there mode official fix  from NextCloud for hassio ?

**Comment by haberda** [comment]
Yes it is non-critical, it's the result of the fact that the upstream container has undergone some structural changes recently and I had to play cat and mouse to keep up. 

If you're at all savvy with docker, another user fixed it on their [instance](https://github.com/haberda/nextcloud-addon/issues/100). If not, I will try and fix it with the next release.

**Comment by awilliams219** [comment]
> Hi Thanks for all and for response... The modification is not saved as soon as i reboot ha on addon ... Would you mind to help in tuto for doing that workaround locally.... I'd prefered to modify the  ref in docker addon but i am not at ease with local declaration of supervisor addons.... Regards 15 mai 2023 22:01:46 Daniel Haber ***@***.***>:

In the interim, you can get it to work by following these steps:

1. In the nextcloud configuration, go to Administration -> Basic Settings
2. Set the cron mode to "webcron" (we're going to use a real cron service, but the webcron setting removes the cron.php entry from the crontab inside the nextcloud docker container)
3. SSH into your homeassistant instance. You may need to install an SSH addon for this.
4. Once SSHed in, run `docker ps | grep nextcloud`
5. Look under the 'NAMES' column to get your nextcloud docker name. I'm not sure if this changes from machine to machine or not. For example, mine is 'addon_1315902c_nextcloud'. Make a note of this value.
6. Run `crontab -e` inside your SSH session
7. Press 'i', then paste the following line to the bottom of the file. Be sure to fill in your docker name where indicated:
    */5     0       0       0       0       docker exec -it {the name you saved in step 5} s6-setuidgid abc php -f /data/config/www/nextcloud/cron.php
  (without the {} brackets)
8. Save and exit by pressing ESCAPE, then typing ':wq' without quotes, but WITH the colon.
9. Type `exit` and press enter
10. Type `exit` and press enter again.

That should configure your homeassistant machine to call the cron script directly, rather than relying on the nextcloud container's internal cron service.

Once haberda is able to fix the issue, you can repeat steps 1-6 then delete the line you pasted in, then repeat steps 8-10 to remove this workaround.

**Comment by awilliams219** [comment]
@aladin2000 

For a temporary workaround, you can set Nextcloud to webcron mode, then make the following changes in hass:

1. Add the following to your homeassistant configuration.yaml:
    
    rest_command:
      nextcloud_webcron:
      url: "{the url of your nextcloud instance}/cron.php"
      method: get

2. Restart Home Assistant
3. Create an automation with a TimePattern trigger. 
    Set the trigger fields to:
      hours: *
      minutes: /5
      seconds: 0
    Set the action to:
      Call Service
        Service: RESTful Command: nextcloud_webcron
4. Save the automation

This will call the cron.php script every five minutes.
